replicaCount: 1
image:
    repository: null
    tag: null
    pullPolicy: IfNotPresent
service:
    name: simplenodeservice
    type: ClusterIP
    externalPort: 80
    internalPort: 8080
container:
    name: simplenodeservice
resources:
    limits:
        cpu: 100m
        memory: 128Mi
    requests:
        cpu: 100m
        memory: 128Mi
